export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    UPLOAD_START: 'USERS_SIGNATURE_UPLOAD_START',
    UPLOAD_PROGRESS: 'USERS_SIGNATURE_UPLOAD_PROGRESS',
    UPLOAD_SUCCESS: 'USERS_SIGNATURE_UPLOAD_SUCCESS',
    UPLOAD_ERROR: 'USERS_SIGNATURE_UPLOAD_ERROR',
    
    LOGOUT: 'USERS_LOGOUT'
};