export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    START_FETCH_PROFILE: 'USERS_START_FETCH_PROFILE',
    FETCH_PROFILE_SUCCESS: 'USERS_FETCH_PROFILE_SUCCESS',
    FETCH_PROFILE_FAILURE: 'USERS_FETCH_PROFILE_FAILURE',

    START_UPDATE_PROFILE: 'USERS_START_UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'USERS_UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: 'USERS_UPDATE_PROFILE_FAILURE',

    START_DELETE_SIGNATURE: 'USERS_START_DELETE_SIGNATURE',
    DELETE_SIGNATURE_SUCCESS: 'USERS_DELETE_SIGNATURE_SUCCESS',
    DELETE_SIGNATURE_FAILURE: 'USERS_DELETE_SIGNATURE_FAILURE',

    UPLOAD_START: 'USERS_SIGNATURE_UPLOAD_START',
    UPLOAD_PROGRESS: 'USERS_SIGNATURE_UPLOAD_PROGRESS',
    UPLOAD_SUCCESS: 'USERS_SIGNATURE_UPLOAD_SUCCESS',
    UPLOAD_ERROR: 'USERS_SIGNATURE_UPLOAD_ERROR',
    RESET_UPLOAD: 'USERS_SIGNATURE_UPLOAD_RESET',
    
    LOGOUT: 'USERS_LOGOUT'
};