export const documentConstants = {
    PREPARE_DOCUMENT_START: 'PREPARE_DOCUMENT_START',
    PREPARE_DOCUMENT_PROGRESS: 'PREPARE_DOCUMENT_PROGRESS',
    PREPARE_DOCUMENT_SUCCESS: 'PREPARE_DOCUMENT_SUCCESS',
    PREPARE_DOCUMENT_ERROR: 'PREPARE_DOCUMENT_ERROR',
    FETCH_REQUEST: 'FETCH_DOCUMENT_REQUEST',
    FETCH_SUCCESS: 'FETCH_DOCUMENT_SUCCESS',
    FETCH_FAILURE: 'FETCH_DOCUMENT_FAILURE',
    FETCH_SINGLE_REQUEST: 'FETCH_SINGLE_DOCUMENT_REQUEST',
    FETCH_SINGLE_SUCCESS: 'FETCH_SINGLE_DOCUMENT_SUCCESS',
    FETCH_SINGLE_FAILURE: 'FETCH_SINGLE_DOCUMENT_FAILURE',
    SIGN_DOCUMENT_REQUEST: 'SIGN_DOCUMENT_DOCUMENT_REQUEST',
    SIGN_DOCUMENT_SUCCESS: 'SIGN_DOCUMENT_DOCUMENT_SUCCESS',
    SIGN_DOCUMENT_FAILURE: 'SIGN_DOCUMENT_DOCUMENT_FAILURE',
    FETCH_PAGE_REQUEST: 'FETCH_DOCUMENT_PAGE_REQUEST',
    FETCH_PAGE_SUCCESS: 'FETCH_DOCUMENT_PAGE_SUCCESS',
    FETCH_PAGE_FAILURE: 'FETCH_DOCUMENT_PAGE_FAILURE'
};
