export const recipientConstants = {
    ADD_RECIPIENT_REQUEST: 'ADD_RECIPIENT_REQUEST',
    ADD_RECIPIENT_SUCCESS: 'ADD_RECIPIENT_SUCCESS',
    ADD_RECIPIENT_FAILURE: 'ADD_RECIPIENT_FAILURE',
    ADD_TAG_REQUEST: 'ADD_TAG_REQUEST',
    ADD_TAG_SUCCESS: 'ADD_TAG_SUCCESS',
    ADD_TAG_FAILURE: 'ADD_TAG_FAILURE',
    ADD_TAG_TO_RECIPIENT_REQUEST: 'ADD_TAG_TO_RECIPIENT_REQUEST',
    ADD_TAG_TO_RECIPIENT_SUCCESS: 'ADD_TAG_TO_RECIPIENT_SUCCESS',
    ADD_TAG_TO_RECIPIENT_FAILURE: 'ADD_TAG_TO_RECIPIENT_FAILURE',
    FETCH_REQUEST: 'RECIPIENT_FETCH_REQUEST',
    FETCH_SUCCESS: 'RECIPIENT_FETCH_SUCCESS',
    FETCH_FAILURE: 'RECIPIENT_FETCH_FAILURE',
    FETCH_TAGS_REQUEST: 'RECIPIENT_FETCH_TAGS_REQUEST',
    FETCH_TAGS_SUCCESS: 'RECIPIENT_FETCH_TAGS_SUCCESS',
    FETCH_TAGS_FAILURE: 'RECIPIENT_FETCH_TAGS_FAILURE'
};