export const userConstants = {
    INVITE_REQUEST: 'USERS_INVITE_REQUEST',
    INVITE_SUCCESS: 'USERS_INVITE_SUCCESS',
    INVITE_FAILURE: 'USERS_INVITE_FAILURE',
    FETCH_REQUEST: 'USERS_FETCH_REQUEST',
    FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
    FETCH_FAILURE: 'USERS_FETCH_FAILURE',
    INVITE_RESET: 'USERS_INVITE_RESET'
};