export const userConstants = {
    INVITE_REQUEST: 'USERS_INVITE_REQUEST',
    INVITE_SUCCESS: 'USERS_INVITE_SUCCESS',
    INVITE_FAILURE: 'USERS_INVITE_FAILURE',
    INVITE_RESET: 'USERS_INVITE_RESET'
};