export const userConstants = {
    INVITE_REQUEST: 'USERS_INVITE_REQUEST',
    INVITE_SUCCESS: 'USERS_INVITE_SUCCESS',
    INVITE_FAILURE: 'USERS_INVITE_FAILURE',
    SEARCH_REQUEST: 'USERS_SEARCH_REQUEST',
    SEARCH_SUCCESS: 'USERS_SEARCH_SUCCESS',
    SEARCH_FAILURE: 'USERS_SEARCH_FAILURE',
    CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
    FETCH_REQUEST: 'USERS_FETCH_REQUEST',
    FETCH_SUCCESS: 'USERS_FETCH_SUCCESS',
    FETCH_FAILURE: 'USERS_FETCH_FAILURE',
    FETCH_PAGE_REQUEST: 'USERS_FETCH_PAGE_REQUEST',
    FETCH_PAGE_SUCCESS: 'USERS_FETCH_PAGE_SUCCESS',
    FETCH_PAGE_FAILURE: 'USERS_FETCH_PAGE_FAILURE',
    INVITE_RESET: 'USERS_INVITE_RESET'
};